### ISSUE TITLE
アカウント連携 押下後 Invalid redirect_uri value. 

### ISSUE THREAD

**Issue by Hokuto47** [shipwebdotjp/wplinelogin#1]
「アカウント連携」 押下後 に
リダイレクトしたあと、

Invalid redirect_uri value.

となり、アクセスができません

恐らくhttpsのリダイレクト先URIが正しくエンコードされていない事が原因のようです。

以下リダイレクトURIの

(https%3A%2F%2Fサーバー名%2Fディレクトリ名%2Flinecallback%2F)

を

(https://サーバー名/ディレクトリ名/Flinecallback/)

と検索窓手入力すれば、LINEのログイン先画面に移動できるので、エンコードが上手くいけば解決するはずです。

phpに詳しくないので、どのように修正すれば正しく読み込むようになるでしょうか?

`https://access.line.me/oauth2/v2.1/authorize?bot_prompt=normal&state=51d※※cdac2※※97bf866e5d41d9&scope=openid%20profile&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fxs90※※.xsrv.jp%2Faf※※ge%2Flinecallback%2F&client_id=16※143※9`

すいません、もしわかれば教えて下さい。

**Comment by shipwebdotjp** [comment]
ご報告ありがとうございます。
こちらの環境ではエンコードされたURLでもLINEログイン画面へ遷移できることを確認しております。

「検索窓手入力」というのは、ブラウザのアドレス欄に表示されているURLのうち
`redirect_uri=https%3A%2F%2Fサーバー名%2Fディレクトリ名%2Flinecallback%2F`
を、
`redirect_uri=http://Fサーバー名/ディレクトリ名/linecallback/`
に書き換えてアクセスするとLINEログイン画面に移動するという事でよろしいでしょうか。

もしかしたらどこかで二重にエンコードされてしまっているのかもしれませんが、どのブラウザでも同じ事象が起こりますでしょうか？
